---
title: "Regression Models Course Project"
author: "Alexander Cherkashin"
date: "Tuesday, May 19, 2015"
output: pdf_document
---

## Summary
In this paper we will look at the data set of a collection of cars that is built in in R (`mtcacars`) and explore the relationship betweeen a set of variables and miles per gallon (MPG). We will find is automatic (A/T) or manual (M/T) transmission is better for MPG and how much better (higher MPG is better).

## Exploratory data analysis
The dimensions of `mtcars` are `r dim(mtcars)` we have 32 different cars and 11 variables. Descrition of variables is available by `?mtcars`. The mean MPG for A/T is `r round(mean(mtcars$mpg[mtcars$am==0]),2)` and for M/T is `r round(mean(mtcars$mpg[mtcars$am==1]),2)`. Looks like M/T is better for MPG, but there are other variables that could affect MPG and thus adjust the transmission effect.

## Relationship between variables and MPG. Model selection.
The simpliest regression model would be just take in account transmission factor variable (`am`): `lm(mpg ~ am, mtcars)` which yields us the intercept coefficients for M/T and A/T. They are just the mean values from previous paragrath. This model is like two horizontal parralell lines at their intersepts with the difference `lm(mpg ~ am, mtcars)$coef[2]` = `r round(mean(mtcars$mpg[mtcars$am==1]),2)` - `r round(mean(mtcars$mpg[mtcars$am==0]),2)` = `r round(lm(mpg ~ am, mtcars)$coef[2],2)`.

But as we said earlier there could be other highly correlated to MPG variables that could adjut the effect. The correlation coefficients between MPG and other variables are: `r paste0(names(cor(mtcars)[,1][-1]),": ",round(cor(mtcars)[,1][-1],2))`

Clearly there are highly correlated variables. But to prevent variance inflation in beta coefficients we should carefully select them and try to select mostly uncorrelated ones. The fist best candidate for regressor is weight (`wt`). It is higly correlated with MPG and at the same time it should affect it from expirience.

##Is an automatic or manual transmission is better for MGP